Feature/new desktop view
CommuneCar/mono-app pull request #179
Opened 2024-06-02 20:18 UTC by Kovler10

missing features:
- closing cards with X button
- creating communities

2024-06-05 08:30 UTC, Zoeshwa requested changes
Cool, I left a few comments, maybe I didn't fully understand the implementation, so if they are unnecessary you can ignore them

2024-06-05 08:30 UTC, Zoeshwa commented on apps/ui/src/Pages/RidesFeed/RidesFeed.tsx
> +    <Page sx={{ width: '100%' }}>
same

2024-06-05 08:30 UTC, Zoeshwa commented on apps/ui/src/Components/Rides/RideList/RideList.tsx
> +    if (!!openDialog) {
is this !! necessary?

2024-06-05 08:30 UTC, Zoeshwa commented on apps/ui/src/Components/Rides/RideList/RideList.tsx
> +  }, [openDialog]);
Is this the best way? Looks a little weird the 2 useEffects

2024-06-05 08:30 UTC, Zoeshwa commented on apps/ui/src/Communities/CommunitiesFeed.tsx
> -      />
where is the add button

2024-06-05 08:30 UTC, Zoeshwa commented on apps/ui/src/DesktopApp/home/home.tsx
> +export { Home };
Feels that there are double things here that can be combined with the display of the mobile

2024-06-06 15:09 UTC, Kovler10 commented on apps/ui/src/Communities/CommunitiesFeed.tsx
> -      />
next to the My communities filter

2024-06-08 14:42 UTC, Zoeshwa approved these changes

2024-06-08 14:44 UTC, merged