Feature/multiple managers
CommuneCar/mono-app pull request #191
Opened 2024-06-12 16:07 UTC by Zoeshwa

2024-06-12 16:57 UTC, Kovler10 requested changes

2024-06-12 17:12 UTC, Zoeshwa commented on apps/ui/src/apis/user/fetchAllUsers.ts
> +export const fetchAllUsers = async (): Promise<UsersSelectorOption[]> => {
I need them for the invitation to the community and to be a community manager. passes them to the component as options

2024-06-12 17:16 UTC, Zoeshwa commented on apps/ui/src/apis/communities/fetchAllCommunities.ts
> +interface AllUserCommunityData {
You're right, but each pull has its own nuances in the context of the type, so I don't know if it's worth trying to make it something generic

2024-06-15 09:06 UTC, Kovler10 approved these changes

2024-06-15 09:07 UTC, merged