Feature/card menu community
CommuneCar/mono-app pull request #65
Opened 2024-05-04 14:12 UTC by Zoeshwa

useUser from sigin or signup  & edit a community

2024-05-04 21:03 UTC, Kovler10 requested changes
Cool! Left some comments

2024-05-04 21:03 UTC, Kovler10 commented on apps/ui/src/Communities/CommunitiesFeed.tsx
> +    setAllCommunitiesDisplay((prev) =>
can we have the communities grouped by their id for faster updating?

2024-05-04 21:03 UTC, Kovler10 commented on apps/ui/src/ProtectedRoute.tsx
> +  if (!user) {
use ternary condition here (`!user ? <> : <>`)

2024-05-08 08:49 UTC, Zoeshwa commented on apps/ui/src/themes/default/consts.ts
> +  REGISTER: "Don't have an account? Register Now",
the format you told me to use is changing ' to " when save - you want me to turn the format off?

2024-05-08 08:52 UTC, Zoeshwa commented on apps/ui/src/hooks/Communities/useGetAllCommunities.tsx
> +    id: '1',
its just a dummy the backend will decide what id contains

2024-05-08 14:43 UTC, Kovler10 approved these changes

2024-05-08 14:43 UTC, merged