Feature/my communities filter
CommuneCar/mono-app pull request #82
Opened 2024-05-11 14:22 UTC by Zoeshwa

2024-05-13 13:40 UTC, Zoeshwa commented
i change the css - tell me what you think :)

2024-05-14 20:43 UTC, Kovler10 requested changes
Nice! Make sure this won't conflict with some of your other PR's

2024-05-14 20:43 UTC, Kovler10 commented on apps/ui/src/Communities/MyEntitiesFilterButton.tsx
> +const MyEntitiesFilterButton: React.FC<MyEntitiesFilterButtonProps> = ({
this component is a bit weird. cannot be reused much

2024-05-14 20:43 UTC, Kovler10 commented on apps/ui/src/Components/PageHeader/PageHeader.tsx
> +const PageHeader: React.FC<PageHeaderProps> = ({ title }) => {
This is great! can you add this to other pages as well?

2024-05-16 15:59 UTC, Kovler10 approved these changes

2024-05-16 15:59 UTC, merged