Added the join ride dialog box
CommuneCar/mono-app pull request #83
Opened 2024-05-11 16:15 UTC by DarNachmani

https://github.com/CommuneCar/mono-app/assets/62894661/4f38efa2-000f-4f75-92b3-17821ce5eeef

2024-05-11 16:17 UTC, DarNachmani commented
@Kovler10 
Don't have the BE request yet - waiting to see in the meeting today the convention of the implementation of the other requests

2024-05-11 16:32 UTC, Kovler10 requested changes
Nice, please remove all js build files

2024-05-11 16:32 UTC, Kovler10 commented on apps/ui/src/Components/JoinRide/JoinRide.tsx
> +import TextField from '@mui/material/TextField';
please put all imports under one @mui/material import

2024-05-11 16:32 UTC, Kovler10 commented on apps/ui/src/Components/JoinRide/JoinRide.tsx
> +interface IJoinRideDialog {
joinRideProps

2024-05-11 16:32 UTC, Kovler10 commented on apps/ui/src/Components/JoinRide/JoinRide.tsx
> +function JoinRideDialog({ isOpen, setOpen }: IJoinRideDialog) {
`const JoinRide: React.FC<JoinRideProps> = ({ isOpen, setIsOpen }) => { `

2024-05-11 16:32 UTC, Kovler10 commented on apps/ui/src/Components/JoinRide/JoinRide.tsx
> +  const [number, setNumber] = useState(1);
number of what?

2024-05-11 16:32 UTC, Kovler10 commented on apps/ui/src/Components/JoinRide/JoinRide.tsx
> +export default JoinRideDialog;
avoid using export default

2024-05-14 15:09 UTC, Kovler10 approved these changes

2024-05-14 15:14 UTC, merged